version: "3.9"

networks:
  ippts-simul-backend:
    driver: bridge

services:
  slave_0:
    build: ./slave
    container_name: slave_0
    environment:
      PORT: 50051
      SLAVEID: 0
    ports:
      - "50051:50051"
    networks:
      - ippts-simul-backend
    restart: on-failure

  slave_1:
    build: ./slave
    container_name: slave_1
    environment:
      PORT: 50052
      SLAVEID: 1
    ports:
      - "50052:50052"
    networks:
      - ippts-simul-backend
    restart: on-failure

  slave_2:
    build: ./slave
    container_name: slave_2
    environment:
      PORT: 50053
      SLAVEID: 2
    ports:
      - "50053:50053"
    networks:
      - ippts-simul-backend
    restart: on-failure

  master:
    build: ./master
    container_name: master
    environment:
      PORT: 5030
      PORT_IO: 5031
    networks:
      - ippts-simul-backend
    ports:
      - "5030:5030"
      - "5031:5031"
    restart: on-failure
