# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  buildall:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
        
  test_master_slave:
    executor: node/default
    steps:
      - run: npm run test

workflows:
  build_all:
    jobs:
      - buildall
  #test_master_slave:
    #jobs:
    #  - buildall
    #  - test_master_slave